### ISSUE TITLE
Support atomic writes

### ISSUE THREAD

**Issue by kevinburke** [shurcooL/vfsgen#35]
Generate() creates a file and then writes chunks to it. This can lead to a situation where someone attempts to compile or run the file if it's only half written.

It would be better to write the file in chunks to a temporary directory and then atomically copy it into place; that way you either get the old file or the new file but not both.

In addition it would probably be useful to wrap the writer in a bufio.NewWriter to avoid a sequence of small writes.

**Comment by shurcooL** [comment]
Thanks for making these improvement suggestions @kevinburke, I'm glad to consider them.

> it would probably be useful to wrap the writer in a bufio.NewWriter to avoid a sequence of small writes.

If I understand correctly, your suggestion is to do a simple drop-in of `bufio.NewWriter` around the `os.File`, is that right? If so, it's something I've considered, but it's not trivial because I use `os.File` methods such as `Seek` and `Truncate`:

https://github.com/shurcooL/vfsgen/blob/f3d80d2d1a3ed83ac7d7a01f14439d635b4d40aa/generator.go#L125

https://github.com/shurcooL/vfsgen/blob/f3d80d2d1a3ed83ac7d7a01f14439d635b4d40aa/generator.go#L60

But [`bufio.Writer`](https://godoc.org/bufio#Writer) doesn't support those.

> Generate() creates a file and then writes chunks to it. This can lead to a situation where someone attempts to compile or run the file if it's only half written.
>
> It would be better to write the file in chunks to a temporary directory and then atomically copy it into place; that way you either get the old file or the new file but not both.

I want to learn more/understand this better before taking action, can you answer a few questions to confirm my understanding please:

Under what conditions did you run into a situation where this was a problem?

I can imagine the most common way of that happening is if you manually interrupt `vfsgendev` while it's running. Then, indeed, you'll have a half-written invalid .go file. Of course, it should be easy to `git checkout` the file to get a previous version of it, or re-run `vfsgendev` without interrupting it to get a new one.

Writing to a temporary folder and then moving it into place adds some complexity (albeit not a lot), so I want to understand the benefits better, so that I can be sure the costs are justified.

Also, from my understanding, other `go generate` tools don't usually take on the responsibility of doing atomic writes. E.g., [this](https://github.com/golang/tools/blob/master/cmd/stringer/stringer.go#L141-L150) is what `stringer` does, it just uses `ioutil.WriteFile` that writes to the file in-place. That's why I am being more cautious here.

One idea to consider is to compute the output file contents completely in memory (complete with seeking and truncating), and then write the entire thing to disk with one call of `ioutil.WriteFile` or so.

Any other information/feedback you have on this is very welcome. Thanks again!

**Comment by kevinburke** [comment]
> Under what conditions did you run into a situation where this was a problem?

Tools like `justrun` do an action actions when a file is modified. In the event where you're issuing many small writes to the file, the tool gets notified about new events, and triggered, many times in a row.

If another tool or another process happens to read the file between write operations, it may read an empty or partially-written file. This may trigger a failed compilation or worse.

`ioutil.WriteFile` issues a single `write` syscall to write the entire file, so it doesn't have the problem listed here.

> One idea to consider is to compute the output file contents completely in memory (complete with seeking and truncating), and then write the entire thing to disk with one call of ioutil.WriteFile or so.

That would be fine, or you can use a tool like github.com/dchest/safefile, which creates a temporary file in the same directory and then renames it into place.

**Comment by shurcooL** [comment]
Most generated files should be quite small, a few MB at most. They'll easily fit into memory.

So, I've decided to go with this strategy:

> One idea to consider is to compute the output file contents completely in memory (complete with seeking and truncating), and then write the entire thing to disk with one call of `ioutil.WriteFile` or so.

It should be a better user experience this way.

Thanks again for the issue report @kevinburke!
