### ISSUE TITLE
Empty filesystem causes "mustUnmarshalTextTime declared and not used" error.

### ISSUE THREAD

**Issue by eBeyond** [shurcooL/vfsgen#42]
Hi,

when compiling (dev-tag NOT set) the generated file I receive an error:

`assets_vfsdata.go:28:2: mustUnmarshalTextTime declared and not used`

This is my assets.go which triggers the generation:

```
//go:generate vfsgendev -source="gitlab.com/eBeyond/tumblr-archiver/data".Assets

// +build dev

package data

import "net/http"

// Assets contains project assets.
var Assets http.FileSystem = http.Dir("assets")
```

**Comment by shurcooL** [comment]
Hi @eBeyond,

Thanks for reporting this. I suspect there are two factors at play here.

First, you’ve probably misaligned your paths, and the `http.Dir("assets")` filesystem ends up being empty rather than containing the contents of your assets directory. Is your assets directory located at gitlab.com/eBeyond/tumblr-archiver/assets? If so, it should be `http.Dir("../assets")` or so instead.

Second, there’s a bug in the code that vfsgen generates when the input filesystem is empty. I will fix that.
