### ISSUE TITLE
Confusing wording in README

### ISSUE THREAD

**Issue by slimsag** [shurcooL/vfsgen#8]
> Outputs gofmt-compatible .go code.

Could be better written as e.g.:

> Outputs preformatted (`gofmt` style) Go code

**Comment by shurcooL** [comment]
How about:

> Outputs `gofmt`ed Go code.

Would that be better?

The Go code it outputs also happens to be idiomatic (with the constraint that its private identifiers should not pollute the user's program, and therefore begin with an underscore) and does not cause `go vet` nor `golint` warnings (aside from `don't use underscores in Go names`).

I didn't quite mention that, but maybe it's worth saying? I kinda prefer not to, because it should be taken for granted. :)

**Comment by shurcooL** [comment]
I've resolved this in 4387efb. Please re-open or leave a comment if there's still room for improvement here.
